---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    Noor. She was always willing to listen, learn, help, and motivate me and she did so without making me feel like an inconvenience and I think those are some core values of this class.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    Recreating graphs. There's a lot of aspects of your graphs that it was hard to keep track of everything but I think the challenge was fun.

3.  What was the easiest part of the class for you? Explain why.\\

    Collaboration, I quickly became comfortable with most of my partners as we both wanted to do our best to get the most out of that experience.

4.  What part of the class surprised or interested you the most? Explain why.

    Lab 5. It was fun to do something that felt less guided and like I was able to do things on my own.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    You take from this class as much as you give into it so try your hardest even if thats not perfect because you can always learn and grow in this class.
